# https://github.com/manna-harbour/miryoku

name: 'Build jorys corne mini cool board'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view", "settings_reset"]'
      alphas: '["qwerty"]'
      extra: '["qwerty"]'
      tap: '["qwerty"]'
      nav: '["vi"]'
      clipboard: '["mac"]'
